version: '3'

services:

  database:
    image: "postgres:16-alpine"
    container_name: postgres
    restart: always

    environment:
      # новопточники сказали как-то по другому передавать пароль
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: zookeeper
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"
#
#  app:
##    image: "dlaaren/zookeeper:latest"
#    container_name: zookeeper-app
#    restart: always
#
#    build:
#      context: ./
#      dockerfile: Dockerfile
#
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/zookeeper
#
#    ports:
#      - "8080:8080"
#    depends_on:
#      - database
