name: Deploy to Hosting
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Hosting
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            eval $(ssh-agent -s)
            ssh-add /root/.ssh/github
            cd my_project/Databases
            git pull
            cd ZooKeeper
            ./gradlew clean build -x test
            docker-compose build
            docker-compose up -d
